UAF-2812 Procurement Cardholder Maintenance, Batch Job
ua-eas/kfs pull request #251
Opened 2017-01-17 22:13 UTC by mmoen

Added new file ProcurementCardHolderInputFileType.java for batch input type for the procurement cardholder job.
Added new file ProcurementCardHolderLoadStep.java This step will call a service method to load the procurement cardholder xml file into the transaction table.
Added new file ProcurementCardHolderUpdateStep.java This step will call a service method to insert/update the procurement card holder records from the loaded procurement card holder table.
Added new file ProcurementCardHolderLoadService.java which provides methods to load batch files for the procurement cardholder batch job.
Added new file ProcurementCardHolderUpdateService.java which provides methods to insert/update procurement card holder records.
Added new file ProcurementCardHolderLoadServiceImpl.java which is the default implementation of the ProcurementCardHolderLoadService interface.
Added new file ProcurementCardHolderUpdateServiceImpl.java which is the default implementation of the ProcurementCardHolderUpdateService interface.
Added new file ProcurementCardHolderLoad.java to represent the procurement cardholder data from the bank.
Modified KFSConstants.java to add a constant for use in other files.
Modified KFSKeyConstants.java to add a constant for use in other files.
Added new file pcdhDigesterRules.xml
Modified fp-resources.properties to add a message.
Modified ojb-fp.xml to add the FP_PRCRMNT_CARD_HLDR_LD_T table.
Modified spring-fp.xml to add the beans needed for the procurementCardHolderJob.
Added new file procurementCardHolder.xsd

2017-01-18 05:21 UTC, nataliac06 requested changes

2017-01-18 05:21 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/ProcurementCardHolderInputFileType.java
> +        return true;
Please confirm there is nothing to validate in the parsedFileContents...

2017-01-18 05:21 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/service/impl/ProcurementCardHolderLoadServiceImpl.java
> +        LOG.info("Total holders loaded: " + Integer.toString(pcardHolders.size()));
No need for the conversion Integer.toString(pcardHolders.size()

2017-01-18 05:21 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/service/impl/ProcurementCardHolderLoadServiceImpl.java
> +        File doneFile = new File(StringUtils.substringBeforeLast(dataFileName, ".") + ".done");
Would like to see a log entry for this method so it's easier to keep track of where the batch process is.

2017-01-18 05:21 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/service/impl/ProcurementCardHolderLoadServiceImpl.java
> +        File doneFile = new File(StringUtils.substringBeforeLast(dataFileName, ".") + ".done");
Also and more important, we need some try/catches here for the file.delete:
try {
Files.delete(path);
} catch (NoSuchFileException x) {
LOG.error....
} catch (IOException x) {
// File permission problems are caught here.
LOG.error(...)
}

2017-01-18 05:21 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/service/impl/ProcurementCardHolderUpdateServiceImpl.java
> +    private static final String GO_LIVE_DATE = "2011-10-01";
Hard coded go_live_date for 2011 used to exclude records that were canceled before this date.

2017-01-18 05:21 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/service/impl/ProcurementCardHolderUpdateServiceImpl.java
> +    private boolean excludeRecord (Date cancelDate) {
Question: Do we still have records that were canceled pre-go live date in 2011?

2017-01-18 05:21 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/service/impl/ProcurementCardHolderUpdateServiceImpl.java
> +    private static final String ACTIVE = "Active";
In the future, we need to remove these hard-coded values and transfer them to a ProcurementCardStatus table

2017-01-18 05:21 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/service/impl/ProcurementCardHolderUpdateServiceImpl.java
> +        LOG.info("Total Procurement Cardholders loaded: " + Integer.toString(loadedPcardHolders.size()));
No need for converting Integer.toString(loadedPcardHolders.size())

2017-01-18 05:21 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/service/impl/ProcurementCardHolderUpdateServiceImpl.java
> +                    updatedRecords = updatedRecords + 1;
LOG.debug statement here to keep track of batch process

2017-01-18 05:21 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/service/impl/ProcurementCardHolderUpdateServiceImpl.java
> +                procurementCardHolderDetails.add(procurementCardHolderDetail);
LOG.debug statement here to keep track of batch process

2017-01-18 05:21 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/service/impl/ProcurementCardHolderUpdateServiceImpl.java
> +                excludedRecords = excludedRecords + 1;
LOG.debug statement here to keep track of batch process

2017-01-18 05:21 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/service/impl/ProcurementCardHolderUpdateServiceImpl.java
> +                LOG.info("Total Procurement Cardholders inserted: " + Integer.toString(insertedRecords));
Please remove all further Integer.toString conversions in the LOG statements. Logger can figure out on its own how to print the objects

2017-01-18 05:21 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/service/impl/ProcurementCardHolderUpdateServiceImpl.java
> +        return statusCode;
Please add a LOG.debug statement at the end of the method to log the resulting statusCode.

2017-01-18 05:21 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/service/impl/ProcurementCardHolderUpdateServiceImpl.java
> +        return cancelCode;
Please add a LOG.debug statement at the end of the method to log the resulting statusCode.

2017-01-18 05:21 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/service/impl/ProcurementCardHolderUpdateServiceImpl.java
> +        return expDate;
Please add a LOG.debug statement at the end of the method to log the resulting expirationDate.

2017-01-18 05:21 UTC, nataliac06 commented on kfs-core/src/main/resources/edu/arizona/kfs/fp/batch/pcdhDigesterRules.xml
> +            <call-method-rule pattern="creditCardNumber" methodname="setCreditCardNumber" paramcount="0" />
Question: Are we missing by any chance creditCardLastFour?

2017-01-18 05:21 UTC, nataliac06 commented on kfs-core/src/main/resources/edu/arizona/kfs/fp/batch/pcdhDigesterRules.xml
> +            <call-method-rule pattern="cardCycleVolumeLimit" methodname="setCardCycleVolumeLimit" paramcount="0" />
Are we sure the cardCycleVolumeLimit field is not supposed to be replaced by cardCycleVolLimit due to the different type in the new implementation?

2017-01-18 05:21 UTC, nataliac06 commented on kfs-web/src/main/webapp/static/xsd/fp/procurementCardHolder.xsd
> +               <xsd:element maxOccurs="1" minOccurs="1" ref="creditCardNumber" />
Just making sure we are not missing creditCardLastFour as a newly added field?

2017-01-18 15:12 UTC, mmoen commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/service/impl/ProcurementCardHolderLoadServiceImpl.java
> +        LOG.info("Total holders loaded: " + Integer.toString(pcardHolders.size()));
fixed

2017-01-18 15:14 UTC, mmoen commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/service/impl/ProcurementCardHolderLoadServiceImpl.java
> +        File doneFile = new File(StringUtils.substringBeforeLast(dataFileName, ".") + ".done");
fixed

2017-01-18 15:16 UTC, mmoen commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/service/impl/ProcurementCardHolderUpdateServiceImpl.java
> +    private static final String GO_LIVE_DATE = "2011-10-01";
Correct. I have confirmed this with Misty

2017-01-18 15:17 UTC, mmoen commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/service/impl/ProcurementCardHolderUpdateServiceImpl.java
> +        LOG.info("Total Procurement Cardholders loaded: " + Integer.toString(loadedPcardHolders.size()));
fixed

2017-01-18 15:33 UTC, mmoen commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/service/impl/ProcurementCardHolderUpdateServiceImpl.java
> +                    updatedRecords = updatedRecords + 1;
fixed

2017-01-18 15:33 UTC, mmoen commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/service/impl/ProcurementCardHolderUpdateServiceImpl.java
> +                procurementCardHolderDetails.add(procurementCardHolderDetail);
fixed

2017-01-18 15:34 UTC, mmoen commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/service/impl/ProcurementCardHolderUpdateServiceImpl.java
> +                excludedRecords = excludedRecords + 1;
fixed

2017-01-18 15:35 UTC, mmoen commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/service/impl/ProcurementCardHolderUpdateServiceImpl.java
> +                LOG.info("Total Procurement Cardholders inserted: " + Integer.toString(insertedRecords));
fixed

2017-01-18 15:39 UTC, mmoen commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/service/impl/ProcurementCardHolderUpdateServiceImpl.java
> +    private boolean excludeRecord (Date cancelDate) {
yes, up to six months prior. Confirmed with Misty

2017-01-18 15:41 UTC, mmoen commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/service/impl/ProcurementCardHolderUpdateServiceImpl.java
> +        return statusCode;
fixed

2017-01-18 15:41 UTC, mmoen commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/service/impl/ProcurementCardHolderUpdateServiceImpl.java
> +        return cancelCode;
fixed

2017-01-18 15:43 UTC, mmoen commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/service/impl/ProcurementCardHolderUpdateServiceImpl.java
> +        return expDate;
fixed

2017-01-18 16:53 UTC, mmoen commented on kfs-core/src/main/resources/edu/arizona/kfs/fp/batch/pcdhDigesterRules.xml
> +            <call-method-rule pattern="creditCardNumber" methodname="setCreditCardNumber" paramcount="0" />
I don't think this is necessary because the last four can be calculated by a substring of the creditCardNumber

2017-01-18 17:21 UTC, mmoen commented on kfs-core/src/main/resources/edu/arizona/kfs/fp/batch/pcdhDigesterRules.xml
> +            <call-method-rule pattern="cardCycleVolumeLimit" methodname="setCardCycleVolumeLimit" paramcount="0" />
Looks like ProcurementCardHolderLoad.java already uses Integer for cardCycleVolumeLimit

2017-01-18 20:16 UTC, mmoen commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/ProcurementCardHolderInputFileType.java
> +        return true;
Confirmed. The parse in ProcurementCardHolderLoadService.java in method loadProcurementCardHolderFile, will validate against data dictionary for ProcurementCardHolderLoad

2017-01-18 20:52 UTC, mmoen commented on kfs-web/src/main/webapp/static/xsd/fp/procurementCardHolder.xsd
> +               <xsd:element maxOccurs="1" minOccurs="1" ref="creditCardNumber" />
Not needed since it is not needed in pcdhDigesterRules.xml

2017-01-18 22:04 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/service/impl/ProcurementCardHolderLoadServiceImpl.java
> +                LOG.info("Loading Procurement Cardholder file " + new File(inputFileName).getName());
Please remove the logging statement as the deletion of the file is already logged in removeDoneFile.

2017-01-18 22:04 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/service/impl/ProcurementCardHolderLoadServiceImpl.java
> +            File doneFile = new File(StringUtils.substringBeforeLast(dataFileName, ".") + ".done");
Replace this code with invoking the other method to avoid code duplication:
removeDoneFile(dataFileName)

2017-01-19 02:33 UTC, nataliac06 approved these changes
All looks good now. Merging the PR.

2017-01-19 02:33 UTC, merged