UAF-3284 : Added Shipping Histories for BI.
ua-eas/kfs pull request #262
Opened 2017-01-30 22:55 UTC by jreeseUA

UAF-3284 : Added code from KFS3 and modified to KFS6 standards to add Shipping Histories for BI.

2017-01-31 06:04 UTC, nataliac06 requested changes

2017-01-31 06:04 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/pdp/businessobject/ShippingHeader.java
> +	/**
Please remove the unused comment lines

2017-01-31 06:04 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/pdp/batch/service/impl/ShippingInvoiceLoadServiceImpl.java
> +        saveShippingData(batchContents, fileName, SpringContext.getBean(DateTimeService.class).getCurrentTimestamp());
Can we inject DateTimeService in the spring config instead of retrieving it from the SpringContext?

2017-01-31 06:04 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/pdp/businessobject/ShippingHeaderHistory.java
> +        return fileName.replace(configurationService.getPropertyValueAsString(KFSConstants.STAGING_DIRECTORY_KEY), "" );
Do we need a check that fileName is never empty/null at this point?

2017-01-31 06:04 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/pdp/businessobject/ShippingHeaderHistory.java
> +            invoices = new ArrayList<ShippingInvoice>( SpringContext.getBean(BusinessObjectService.class).findMatching(ShippingInvoiceHistory.class,criteria) );
Can we inject the BusinessObject Service through the spring configuration instead of finding it in the SpringContext?

2017-01-31 06:04 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/pdp/businessobject/ShippingHeaderHistory.java
> +    /**
Unused comment lines, should be removed.

2017-01-31 06:04 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/pdp/businessobject/ShippingHeader.java
> +            invoices = new ArrayList<ShippingInvoice>( SpringContext.getBean(BusinessObjectService.class).findAll(ShippingInvoice.class) );
Can we use injection for BusinessObjectService instead of finding it in the SpringContext?

2017-01-31 06:04 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/pdp/businessobject/ShippingHeader.java
> +        if ( !invoicesLoaded ) {
Not sure if we need a boolean for invoicesLoaded, if invoices is null or isEmpty() can suffice.

2017-01-31 06:04 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/pdp/businessobject/ShippingHeaderHistory.java
> +        if ( !invoicesLoaded ) {
We might not need invoicesLoaded boolean, invoices == null or invoices.isEmpty() should suffice.

2017-01-31 06:04 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/pdp/businessobject/ShippingInvoiceHistory.java
> +    /**
Another unused comment section.

2017-01-31 06:04 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/pdp/businessobject/ShippingInvoiceTracking.java
> +    /**
Copy/paste empty comment.

2017-01-31 06:04 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/pdp/businessobject/ShippingInvoiceTrackingHistory.java
> +    /**
Unused comment block.

2017-01-31 06:04 UTC, nataliac06 commented on kfs-core/src/main/resources/edu/arizona/kfs/pdp/ojb-pdp.xml
> +    <field-descriptor name="loadDate" column="LOAD_DT" jdbc-type="TIMESTAMP" primarykey="true"/>
Missing REBILL_IND and SHIP_DT columns from the table, not sure if it's intentional.

2017-02-01 00:37 UTC, jreeseUA commented on kfs-core/src/main/resources/edu/arizona/kfs/pdp/ojb-pdp.xml
> +    <field-descriptor name="loadDate" column="LOAD_DT" jdbc-type="TIMESTAMP" primarykey="true"/>
I originally added these (REBILL_IND and SHIP_DT) and mentioned it to Julie.  She said that those columns came over from KFS3 in the KFSDBUpgrade but weren't used in KFS6 and should not be added in code so the columns would be easier to remove from the table later.

2017-02-01 16:14 UTC, nataliac06 approved these changes
Thanks for the explanations, Jim. Code looks Ok.

2017-02-06 23:49 UTC, merged