UAF-2967 Procurement Card Reconciliation Step 4 (Postback)
ua-eas/kfs pull request #283
Opened 2017-02-23 16:52 UTC by mmoen

Modified ProcurementCardCreateDocumentServiceImpl.java to set the description the same way it is done in KFS 3.0. This fixes the issue where backpost is allowed and the description is changed to add additional text to the beginning of the descripition. When the GLPE's were saved, transactionLedgerEntryDescription was over the maximum 40 characters the database allows for that field.
Modified ProcurementCardDocument.java to override the customizeExplicitGeneralLedgerPendingEntry method to include backposting, plus helper methods.

2017-02-23 18:17 UTC, nataliac06 requested changes

2017-02-23 18:17 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/service/impl/ProcurementCardCreateDocumentServiceImpl.java
> +        if (cardHolderName.length() > 24) {
Please add a constant in the PcardDocument for the cardHolderNameMaxLength and replace the hard-coded 24 value.

2017-02-23 18:17 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/fp/document/ProcurementCardDocument.java
> +            if( !getDocumentHeader().getDocumentDescription().contains("FY " + prevFiscYr) ) {
Please refactor the if statement:
String documentDescription = getDocumentHeader().getDocumentDescription();
if ( StringUtils.isNotEmpty(documentDescription) && documentDescription.contains("FY ....){
    getDocumentHeader().setDocumentDescription("FY "+prevFiscYr+" " + documentDescription);
}
Do we have an idea regarding what to do if the documentDescription is empty? Is there a default value we should set it to?

2017-02-23 18:17 UTC, nataliac06 commented on kfs-core/src/main/java/edu/arizona/kfs/fp/document/ProcurementCardDocument.java
> +        int allowBackpost = (Integer.parseInt(parameterService.getParameterValueAsString(ProcurementCardLoadStep.class, ALLOW_BACKPOST_DAYS)));
Please separate this in two steps:
String allowBackpostParam = parameterService.getParameter.....
int allowBackpost = 0; -> also please check if this is an OK default value  
if (StringUtils.isNotEmpty() && StringUtils.isNumeric( allowBackPostDyas ) ){
    allowBackpost = Integer.parseInt( allowBackpostParam );
}

2017-02-23 19:46 UTC, mmoen commented on kfs-core/src/main/java/edu/arizona/kfs/fp/batch/service/impl/ProcurementCardCreateDocumentServiceImpl.java
> +        if (cardHolderName.length() > 24) {
fixed

2017-02-23 20:46 UTC, mmoen commented on kfs-core/src/main/java/edu/arizona/kfs/fp/document/ProcurementCardDocument.java
> +            if( !getDocumentHeader().getDocumentDescription().contains("FY " + prevFiscYr) ) {
Fixed. As for the documentDescription, Misty said the value is  the credit card last four digits and card name, which is being set in the createAndValidateAccountingLines method of (edu/arizona)ProcurementCardCreateDocumentServiceImpl.java.

2017-02-24 03:09 UTC, nataliac06 commented
Looks good.

2017-02-24 03:09 UTC, merged