UAF-3159 / UAF-31 Check Reconciliation module
ua-eas/kfs pull request #327
Opened 2017-04-05 19:13 UTC by adamkost

Code Feature for the Check Reconciliation module UAF-3159

Functional specs available at https://jira.arizona.edu/browse/UAF-3159

2017-04-13 19:40 UTC, sskinner requested changes
Great job! Awesome first review, little nits to address, and we'll get the merge going.

2017-04-13 19:40 UTC, sskinner commented on kfs-cr/src/main/java/edu/arizona/kfs/module/cr/batch/service/impl/CheckReconciliationImportBatchServiceImpl.java
> +                success = false;
No-op, can be deleted.

2017-04-13 19:40 UTC, sskinner commented on kfs-cr/src/main/java/edu/arizona/kfs/module/cr/batch/service/impl/CheckReconciliationImportBatchServiceImpl.java
> +            } finally {
No-op, can deleted.

2017-04-13 19:40 UTC, sskinner commented on kfs-cr/src/main/java/edu/arizona/kfs/module/cr/batch/service/impl/CheckReconciliationImportBatchServiceImpl.java
> +    private void processFile(File file) throws Exception {
Please ensure a finally block closes the BufferedReader.

2017-04-13 19:40 UTC, sskinner commented on kfs-cr/src/main/java/edu/arizona/kfs/module/cr/service/impl/CheckReconciliationReportServiceImpl.java
> +        out.flush();
Let's make sure to use 'finally' to close resources.

2017-04-13 19:40 UTC, sskinner commented on kfs-cr/src/main/java/edu/arizona/kfs/module/cr/service/impl/CheckReconciliationReportServiceImpl.java
> +        WebUtils.saveMimeOutputStreamAsFile(response, KFSConstants.ReportGeneration.PDF_MIME_TYPE, baos, CrConstants.CR_REPORT_FILE_NAME + KFSConstants.ReportGeneration.PDF_FILE_EXTENSION);
A try/finally right here for baos?

2017-04-13 19:50 UTC, adamkost commented on kfs-cr/src/main/java/edu/arizona/kfs/module/cr/batch/service/impl/CheckReconciliationImportBatchServiceImpl.java
> +                success = false;
Fixed.

2017-04-13 19:50 UTC, adamkost commented on kfs-cr/src/main/java/edu/arizona/kfs/module/cr/batch/service/impl/CheckReconciliationImportBatchServiceImpl.java
> +            } finally {
Fixed.

2017-04-13 20:07 UTC, adamkost commented on kfs-cr/src/main/java/edu/arizona/kfs/module/cr/batch/service/impl/CheckReconciliationImportBatchServiceImpl.java
> +    private void processFile(File file) throws Exception {
Finally and additional try blocks added at potential exception points, closing the BufferedReader before throwing exceptions.

2017-04-13 20:11 UTC, adamkost commented on kfs-cr/src/main/java/edu/arizona/kfs/module/cr/service/impl/CheckReconciliationReportServiceImpl.java
> +        out.flush();
Fixed.

2017-04-13 20:16 UTC, adamkost commented
changes ready for review.

2017-04-14 01:45 UTC, sskinner approved these changes
Looks awesome, thanks for the quick turn-around!

2017-04-14 01:45 UTC, merged